version: "3.8"

services:
  rabbitmq_server:
    image: rabbitmq:3.9-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017